// src/App.vue
<script setup lang="ts">
import axios from 'axios'
import { ref, onMounted } from 'vue'

const user = ref('')

onMounted(async () => {
  let token = localStorage.getItem('token')
  if (token) {
    await axios.get('http://localhost:3000/api/user', {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    })
    .then(res => {
      user.value = res.data
      console.log(user.value)
    })
    .catch(err => {
      console.log(err)
    })
  }
})
</script>

<template>
  <div id="app">
    <Navbar/>
    <router-view :user="user"/>
  </div>
</template>

<style>
</style>

// frontend/src/App.tsx
import { useState, Fragment, useEffect, createContext } from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';

import Home from './pages/Home'
import About from './pages/About'
import Ressources from './pages/Ressources';
import Navbar from './components/Navbar'
import Footer from './components/Footer';
import Login from './pages/Connection';

const UserContext = createContext(null);

function App() {

  const [user, setUser] = useState(null);

  useEffect(() => {
    const token = localStorage.getItem('token');
    console.log(token);
    if (token) {
      fetch('http://localhost:3000/api/users/me', {
        headers: {
          Authorization: `Bearer ${token}`
        }})
        .then(response => response.json())
        .then(data => {
          setUser(data);
        })
    }
  }, [])
    

  return (
    <Fragment>
        <Router>
          <UserContext.Provider value={user}>
            <Navbar />
            <Routes>
              <Route path="/" element={<Home />} />
              <Route path="/about" element={<About />} />
              <Route path="/ressources" element={<Ressources />} />
              <Route path="/login" element={<Login />} />
            </Routes>
            <Footer />
          </UserContext.Provider>
        </Router>
    </Fragment>
  )
}

export default App

export { UserContext }
